= README
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:
:toc-placement!:

toc::[]


== Overview

These documents were written using AsciiDoctor! I chose AsciiDoctor because it is an advanced markup language that is supported on GitHub!

IMPORTANT: I am going to primarily write these documents for GitHub! I will avoid any AsciiDoctor feature that is not supported on GitHub.


== Looking for the Tizen Docs?

<<index#,The Tizen docs are right here!>>


== Install AsciiDoctor

link:https://rubygems.org/gems/asciidoctor[The official guide for installing AsciiDoctor] is pretty straight forward.


== Building the Docs

== GitHub

GitHub seems to do a pretty good job of rendering AsciiDoctor files.

The only incompatibility I have come across so far is that GitHub does not support the `include::<adoc-file>[]` directive. __This seems to be for security reasons.__

=== HTML

HTML backend is supported out of the box! Just run this command:

`asciidoctor index.adoc`

=== PDF

To build PDFs you will need to link:https://rubygems.org/gems/asciidoctor-pdf[install this extension.]

Once that is installed simply run this command:

`asciidoctor-pdf index.adoc`


== Text Editor Plugins

=== Atom Plugin

The official plugin pack for the Atom text editor is available link:https://atom.io/packages/asciidoc-assistant[here].

=== VS Code Plugin

A official__*__ plugin for VS Code is available link:https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode[here].

__* The repo does seem to hosted on the link:https://github.com/asciidoctor/asciidoctor-vscode[AsciiDoctor GitHub Account].__

=== Other Plugins

A list of other plugins is available link:https://asciidoctor.org/docs/editing-asciidoc-with-live-preview/[here].


== AsciiDoctor References

* link:https://asciidoctor.org/docs/user-manual/[The AsciiDoctor User Manual]
** link:https://asciidoctor.org/docs/user-manual/#navigating-between-source-files[Linking to Other Documents in GitHub]
