ifdef::env-github[]
toc::[]
endif::[]

= TODO (Author's Notes)

* Make sure the document is formatted correctly on GitHub (GitHub Flavored AsciiDoc)
* It would be nice to have a post-push Git script that could update a Confluence page, unless that defeats the purpose of a Confluence page?


= Building the Tizen App

`./generate.rb -p tizen-nacl -m Developer -c [Release, Debug]`

`./build.rb -b build/tizen-nacl/[Release, Debug]/ -c [Release, Debug]`


= Installing the Tizen App on a TV

Need to be connected tp the TV before the app can be installed. It is easiest to only connect to one TV at a time, that way you don't need to specify the target for the install command.

I would recommend using the `device-manager` for connecting to the TVs.


`tizen install -n build/tizen-nacl/[Release, Debug]/localnow-[Release, Debug].wgt`


== Why is the App not Installing?

Probably certificate issue.

- Make sure you are using the correct Cert (and that it is not a Tizen Cert)
  - You can see what Cert was used to sign the package in the last few lines of output from the build command
  - To change the default Cert see above
- Make sure the TV is whitelisted on the Cert you are using
- Make sure that the Cert is installed on the TV


== Why the Hell is the App not Installing!?

Error 116 usually means there is too little space on TV to install the widget.

TIP: Release builds are smaller than Debug builds. Debug builds also aren't useful without a debug TV. Although, some work needs to be done to get remote logging and debug level logs.


=== Clearing Memory on the TV

The best bet for clearing memory on the TV is to do a factory reset. There are several different types of "reset" available and they will be described later in this chapter.

When reseting remember to do the following:

==== Terms and Conditions Screen

Only accept the first option in the Terms and Conditions seems to stop some built in widgets from being installed.


==== Auto Update

In the App -> Settings (Gear Icon) menu disable auto updates.


==== Change Location

During the reset you will see a Terms and Conditions screen.

At this screen press the following on an IR remote:

`FF, 2, 8, 9, RW`

Select a country such as Cayman Islands, Cuba, or Zimbabwe.


=== Factory Reset?


=== Reset Smarthub?


=== Reset?


=== Start Setup?


=== Other Factory Reset? (From Factory Menu)

There is a hidden Factory Reset option in the Factory Menu on the TV.
To get to the Factory Menu:

. Put the tv to sleep by pressing the power button
. Wait 5 seconds
. On the IR remote press the following `Mute, 1, 8, 2, Power`
. If the TV displays the Samsung Smart TV logo then you likely entered the code correctly
. Wait for the TV to start and a black and blue menu to appear in the top left of the screen
. Select _Options_
. Select _Factory Rest_
. The TV will turn off
. Press the power button to turn the TV back on



== Why God!? Why!?

If the memory is at 0.00mb and you have tried everything suggested here then I am sad to say the TV has passed on. RIP in Peace Samsung Tizen TV, we hardly knew thee.
ifdef::env-github[]
:ghost: :cry: :poop:
endif::[]
ifndef::env-github[]
&#128123; &#128546; &#128169;
endif::[]

= Debugging the Tizen App

If you have made it this far then you are one of the lucky ones...

Unfortunetly for you, debugging an app on Tizen is an arcaine art. I have never seen a Tizen Development TV with my own eyes, but many spread rumours of their existance. Even if they do exist the chances of finding one in the wild is unlikely.

In order to hear what your TV has to say you need to teach it to use a remote debugging script.

https://github.com/YOU-i-Labs/Commons/tree/master/sandbox/tizen_remote_console


= Show Me the Magic (Commands)

There is an ancient command passed down from Tizen developers before. It seems to work on some TVs and not on others -- perhaps newer TVs are immune to this incantation. It seems to cause the TV to forget the widget file that was last in its memory.

Enough talk! The spell is as follows: `sdb shell "0 rmfile any_string"`

WARNING: Be weary of special quotation marks when thou copy and pasteth this command as they can cause the spell to fail.
